### ISSUE TITLE
Refactor to build ARM container on runner M1 instances

### ISSUE THREAD

**Issue by zack-is-cool** [defenseunicorns/build-harness#115]
Available as of 10/02/23
https://github.com/actions/runner-images/issues/8439

This will speed up build-harness arm container creation

**Comment by RothAndrew** [comment]
It's $0.16 per minute... compared to our price right now of free I'm not sure the value is there to use them.

**Comment by zack-is-cool** [comment]
Yeah.. I realized that after making this issue. Maybe they will eventually make a free arm runner.

**Comment by RothAndrew** [comment]
Closing in favor of #121
