### ISSUE TITLE
Improve ARM build speed

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/build-harness#121]
How might we improve the ARM build speed? Currently it is about 17 minutes, compared to x86 build speed of 7 minutes.

Ideas:
- Use GitHub's [new Apple M1 runner](https://github.com/actions/runner-images/issues/8439) -- $0.16/minute x 10x multiplier for macos == $1.60/minute -- woof
- ??

Definition of Done:
- ARM build speed is faster than it is now

**Comment by zack-is-cool** [comment]
https://github.com/actions/runner-images/issues/5631 👀

**Comment by kgantchev** [comment]
> * Use GitHub's [new Apple M1 runner](https://github.com/actions/runner-images/issues/8439) -- $0.16/minute -- woof

Might I make a suggestion here? You can try the [FlyCI](https://www.flyci.net/)'s M1 and M2 runners which are on average about 2x faster and 2x cheaper than GitHub's runners. We also offer a free tier of 500 mins/month on the M1 runner for OSS projects.

## Pricing  

| Processor | vCPU | RAM (GB) | Storage | Label                          | Price on FlyCI | Price on GitHub |
|-----------|------|----------|---------|--------------------------------|----------------|-----------------|
| M1        | 4    | 7        | 28 GB   | flyci-macos-large-latest-m1    | $0.06          | -             |
| M1        | 8    | 14       | 28 GB   | flyci-macos-xlarge-latest-m1   | $0.12          | $0.16           |
| M2        | 4    | 7        | 28 GB   | flyci-macos-large-latest-m2    | $0.08          | -             |
| M2        | 8    | 14       | 28 GB   | flyci-macos-xlarge-latest-m2   | $0.16          | -             |

## Guide for Implementation

1. Install the [FlyCI GitHub app](https://github.com/apps/flyci-prod).
2. Modify the `runs-on` directive in workflow files as demonstrated in this PR.
4. Enjoy enhanced efficiency in CI builds with the integration of FlyCI's MacOS runners.

```diff
jobs:
 ci:
-    runs-on: macos-latest
+    runs-on: flyci-macos-large-latest-m1
   steps:
   - name: 👀 Checkout repo
     uses: actions/checkout@v4
```
 
We'll be very happy to have you on board.

**Comment by RothAndrew** [comment]
Request has been submitted for ARM runner support. BuildJet looks the most promising to me at the moment. Corp Security is looking into it.

**Comment by RothAndrew** [comment]
OBE, we determined that our reasons for needing to build the arm64 image no longer apply. We are instead deciding to stop building the arm64 image
