### ISSUE TITLE
Docker, question mark?

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/build-harness#8]
This section intentionally left blank...

**Comment by RothAndrew** [comment]
discuss

**Comment by blancharda** [comment]
#someday
...Maybe.

**Comment by RothAndrew** [comment]
Here be dragons

**Comment by blancharda** [comment]
But for reals...
It might be nice to have support for this. But mounting the docker sock in a CI image probably isn't a great practice to encourage 🤔

**Comment by RothAndrew** [comment]
I'm not completely opposed to having Docker installed in Build Harness as long as we document the dangers.

**Comment by RothAndrew** [comment]
I think there's plenty of demand for this, let's get it added. I'll get started on it.

Probably won't be able to use ASDF to do the install but that shouldn't be a huge deal.
